from datetime import datetime


class WEAVER:

    def build_report(self, parsed, radar, judge):

        title = parsed.get("title", "Unknown Project")

        date = datetime.now().strftime("%d-%m-%Y")

        report = f"""
<h1 style='color:#0d6efd;'>🚀 PRISM AI Feasibility Report</h1>

<hr>

<h2>📌 Project Overview</h2>

<p><b>Project:</b> {title}</p>
<p><b>Generated By:</b> PRISM AI Engine</p>
<p><b>Date:</b> {date}</p>

<hr>

<h2>🧭 Executive Summary</h2>

<p>
PRISM analyzed the uploaded project specification and evaluated:
</p>

<ul>
<li>Technical feasibility</li>
<li>System architecture complexity</li>
<li>Development effort</li>
<li>Implementation risks</li>
<li>Recommended engineering patterns</li>
</ul>

<hr>

<h2>📋 Feature Feasibility Analysis</h2>
"""

        # ------------------------------------------------
        # FEATURE ANALYSIS
        # ------------------------------------------------

        for i, feature in enumerate(parsed["features"]):

            j = judge[i]

            # Risk color
            risk_color = "#198754"

            if j["risk"] == "medium":
                risk_color = "#ffc107"

            elif j["risk"] == "high":
                risk_color = "#dc3545"

            report += f"""

<div style='
border:1px solid #ddd;
border-radius:10px;
padding:20px;
margin-bottom:20px;
background:#f8f9fa;
'>

<h3 style='color:#0d6efd;'>
Feature {i+1}: {feature['name']}
</h3>

<p>
<b>Feasibility:</b>
<span style='color:green;'>✔ {j['feasible'].upper()}</span>
</p>

<p>
<b>Risk Level:</b>
<span style='color:{risk_color};'>
{j['risk'].upper()}
</span>
</p>

<p>
<b>Development Effort:</b>
{j['effort'].capitalize()}
</p>

<h4>⚠ Key Considerations</h4>

<ul>
"""

            if j["reasons"]:

                for reason in j["reasons"]:
                    report += f"<li>{reason}</li>"

            else:
                report += "<li>No major technical risks detected</li>"

            report += "</ul></div>"

        # ------------------------------------------------
        # RESEARCH PATTERNS
        # ------------------------------------------------

        report += """
<hr>

<h2>🔍 Recommended Engineering Patterns</h2>
"""

        for pattern in radar["patterns"]:

            report += f"""

<div style='
border-left:5px solid #0d6efd;
background:#eef4ff;
padding:15px;
margin-bottom:15px;
border-radius:8px;
'>

<h4>{pattern['topic']}</h4>

<p>
<b>Recommended Approach:</b>
{pattern['approach']}
</p>

<p>
<b>Implementation Notes:</b>
{pattern['notes']}
</p>

</div>
"""

        # ------------------------------------------------
        # MATRIX
        # ------------------------------------------------

        report += """
<hr>

<h2>📊 Effort & Risk Matrix</h2>

<table border="1" cellspacing="0" cellpadding="10" width="100%">
<tr style="background:#0d6efd;color:white;">
<th>Feature</th>
<th>Feasible</th>
<th>Risk</th>
<th>Effort</th>
</tr>
"""

        for i, feature in enumerate(parsed["features"]):

            j = judge[i]

            report += f"""
<tr>
<td>{feature['name']}</td>
<td>{j['feasible']}</td>
<td>{j['risk']}</td>
<td>{j['effort']}</td>
</tr>
"""

        report += "</table>"

        # ------------------------------------------------
        # FINAL CONCLUSION
        # ------------------------------------------------

        report += """

<hr>

<h2>🚀 Final Technical Conclusion</h2>

<div style='
background:#e9f7ef;
padding:20px;
border-radius:10px;
border-left:6px solid green;
'>

<p>
The proposed system is technically feasible and can be implemented successfully using a modular FastAPI architecture.
</p>

<h3>✅ Recommended Development Roadmap</h3>

<ol>
<li>Implement authentication and authorization system</li>
<li>Build core dashboard modules</li>
<li>Develop file/document management</li>
<li>Integrate analytics and reporting</li>
<li>Implement payment gateway in final phase</li>
<li>Perform security hardening and testing</li>
</ol>

</div>

<hr>

<h3 style='text-align:center;color:gray;'>
Generated by PRISM AI Analysis Engine
</h3>
"""

        return report